### ISSUE TITLE
Error during test.

### ISSUE THREAD

**Issue by mhf-ir** [Adelost/javascript-serialization-benchmark#2]
Arguments [ 'testJson' ]
TEST JSON
TOTAL TIME: 50.31 s
(node:10810) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/sweb/tmp/javascript-serialization-benchmark/src/tmp/plot.json'
    at Object.openSync (fs.js:465:3)
    at Object.writeFileSync (fs.js:1416:35)
    at loadPlotData (/sweb/tmp/javascript-serialization-benchmark/src/utils/helper.ts:130:8)
    at savePlotData (/sweb/tmp/javascript-serialization-benchmark/src/utils/helper.ts:136:16)
    at Object.<anonymous> (/sweb/tmp/javascript-serialization-benchmark/src/utils/helper.ts:67:3)
    at Generator.next (<anonymous>)
    at fulfilled (/sweb/tmp/javascript-serialization-benchmark/src/utils/helper.ts:5:58)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10810) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10810) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mhf-ir** [comment]
Fixed and improved.
https://github.com/Adelost/javascript-serialization-benchmark/pull/3
